name: Build and Test

on: push

jobs:
  run-msbuild-vstest:
    name: Run MSBuild and VSTest

    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Setup Nuget
        uses: nuget/setup-nuget@v1

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup VSTest
        uses: darenm/setup-vstest@v1

      - name: Restore NuGet Packages
        run: nuget restore src/MollieApi.Net.sln

      - name: Build Solution
        run: msbuild src/MollieApi.Net.sln /p:Configuration=Release

      - name: Run VSTest
        run: vstest.console src/MollieApi.Tests/bin/Release/MollieApi.Tests.dll

