name: Tests

on: push

jobs:
  build:
    name: Unit Testing

    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup Nuget
        uses: nuget/setup-nuget@v1

      - name: Restore NuGet Packages
        run: nuget restore src/MollieApi.Net.sln

      - name: Build Solution
        run: msbuild src/MollieApi.Net.sln /p:Configuration=Release

      - name: Run Unit Tests
        run: vstest.console.exe src/MollieApi.Tests/bin/Release/MollieApi.Tests.dll

